# .github/workflows/test-module.yml
name: Test PsLocations Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester -Script PsLocations/tests/PsLocations.tests.ps1 -PassThru -CI
          
