# .github/workflows/test-module.yml
name: Test PsLocations Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Install Pester
        run: |
          pwsh -Command 'Install-Module -Name Pester -Force -Scope CurrentUser'

      - name: Run Pester tests
        run: |
          pwsh -Command 'Invoke-Pester -Script "tests/PsLocations.tests.ps1"'
          