# .github/workflows/test-module.yml
name: Test PsLocations Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Import-Module PSScriptAnalyzer
          displayName: 'Install PSScriptAnalyzer'
    
      - name: |
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path . -Recurse
          if ($results.Count -gt 0) {
            Write-Output "Script Analyzer found issues:"
            $results | Format-Table
            exit 1
          }
          displayName: 'Run PSScriptAnalyzer'
      
      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester -Script PsLocations/tests/PsLocations.tests.ps1 -PassThru -CI
          displayName: 'Run Pester tests'
          